Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-03, with the labels that each got.

#912 TextView: Allow linking text with a pasted URL
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Enhancement

#916 Issue/915 set and remove link
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Bug

#918 NSParagraphStyle's isEqual now compares correctly against ParagraphStyle.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/NSAttributedString+Attachments.swift
  Aztec/Classes/Extensions/NSMutableAttributedString+ParagraphProperty.swift
  Aztec/Classes/TextKit/ParagraphStyle.swift
  AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
  AztecTests/NSMutableAttributedStringParagraphProperty.swift
  AztecTests/ParagraphStyleTests.swift
Labels: [Type] Bug

#903 Feature/452 add support for code element
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/NSAttributedString+Analyzers.swift
  Aztec/Classes/Extensions/NSAttributedStringKey+Aztec.swift
  Aztec/Classes/Formatters/Implementations/CodeFormatter.swift
  Aztec/Classes/GUI/FormatBar/FormattingIdentifier.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  Aztec/Classes/TextKit/TextView.swift
  Example/Example/EditorDemoController.swift
  Example/Example/SampleContent/content.html
Labels: [Type] Discussion, [Type] Enhancement

#920 Fixes the isEqual method we swizzled.
  Aztec/Classes/TextKit/ParagraphStyle.swift
Labels: [Type] Bug

#922 Fixes undo for captions.
  Aztec/Classes/TextKit/TextView.swift
  Example/Example/AttachmentDetailsViewController.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Tech Debt / Tech Task
