Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-09, with the labels that each got.

#1044 Adds more unit tests.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/UIImage+Resize.swift
  Aztec/Classes/Renderers/HTMLAttachmentRenderer.swift
  AztecTests/Extensions/UIImageResizeTests.swift
  AztecTests/Renderers/HTMLAttachmentRendererTests.swift
  AztecTests/Resources/HTMLAttachmentRender_2x.png.dat
  AztecTests/Resources/HTMLAttachmentRender_3x.png.dat
  AztecTests/Resources/README.md
  AztecTests/Resources/UIImageResizeImage1_2x.png.dat
  AztecTests/Resources/UIImageResizeImage1_3x.png.dat
  AztecTests/Resources/UIImageResizeImage2_2x.png.dat
  AztecTests/Resources/UIImageResizeImage2_3x.png.dat
  AztecTests/Resources/aztec.png
  AztecTests/Resources/content.html
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/CaptionShortcode/CaptionShortcodeInputProcessor.swift
  WordPressEditor/WordPressEditorTests/Resources/GutenpackAttachmentRender_2x.png.dat
  WordPressEditor/WordPressEditorTests/Resources/GutenpackAttachmentRender_3x.png.dat
  WordPressEditor/WordPressEditorTests/Resources/README.md
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/CaptionShortcode/CaptionShortcodeInputProcessorTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenpackAttachmentRendererTests.swift
  docs/index.html
Labels: [Type] Tech Debt / Tech Task

#1045 Adds some more unit tests and fixes some documentation
  Aztec.xcodeproj/project.pbxproj
  AztecTests/Renderers/CommentAttachmentRendererTests.swift
  AztecTests/Resources/CommentAttachmentRender_2x.png.dat
  AztecTests/Resources/CommentAttachmentRender_3x.png.dat
  AztecTests/Resources/README.md
  WordPressEditor/WordPressEditorTests/Resources/README.md
  docs/index.html
Labels: [Type] Tech Debt / Tech Task

#1049 fixed regular expression range issue
  Aztec/Classes/Extensions/NSTextingResult+Helpers.swift
  Aztec/Classes/Processor/RegexProcessor.swift
Labels: [Priority] High, [Type] Bug

#1050 Updatest README.md for v1.0.
  README.md
Labels: [Type] Documentation

#1051 Removes CHANGELOG.md (for now).
  CHANGELOG.md
Labels: [Type] Documentation

#1053 Fixes a data loss issue.
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
Labels: [Priority] High, [Type] Bug

#1062 Fixes some issues when pasting content from Google Docs.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Converters/Attributes/Base/ElementAttributeConverter.swift
  Aztec/Classes/Converters/Attributes/Base/MainAttributesConverter.swift
  Aztec/Classes/Converters/Attributes/Implementations/BoldElementAttributeConverter.swift
  Aztec/Classes/Converters/Attributes/Implementations/ItalicElementAttributeConverter.swift
  Aztec/Classes/Converters/Attributes/Implementations/UnderlineElementAttributeConverter.swift
  Aztec/Classes/Converters/ElementsToHTML/Base/ElementToStringConverter.swift
  Aztec/Classes/Converters/ElementsToHTML/Implementations/GenericElementToTagConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Base/AttachmentElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Base/ElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Base/FormatterElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Implementations/BRElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Implementations/CiteElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Implementations/FigcaptionElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Implementations/FigureElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Implementations/GenericElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Implementations/HRElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Implementations/ImageElementConverter.swift
  Aztec/Classes/Converters/ElementsToNSAttributedString/Implementations/VideoElementConverter.swift
  Aztec/Classes/Converters/HTMLToElements/CLinkedListToArrayConverter.swift
  Aztec/Classes/Converters/HTMLToElements/Converter.swift
  Aztec/Classes/Converters/NSAttributedStringToElements/Base/ConditionalStringAttributeConverter.swift
  Aztec/Classes/Converters/NSAttributedStringToElements/Base/StringAttributeConverter.swift
  Aztec/Classes/Converters/NSAttributedStringToElements/ConditionalConverters/ConditionalItalicStringAttributeConverter.swift
  Aztec/Classes/Converters/NSAttributedStringToElements/Implementations/BoldStringAttributeConverter.swift
  Aztec/Classes/Converters/NSAttributedStringToElements/Implementations/CiteStringAttributeConverter.swift
  Aztec/Classes/Converters/NSAttributedStringToElements/Implementations/ItalicStringAttributeConverter.swift
  Aztec/Classes/Converters/NSAttributedStringToElements/Implementations/UnderlineStringAttributeConverter.swift
  Aztec/Classes/Libxml2/DOM/Data/Attribute.swift
  Aztec/Classes/Libxml2/DOM/Data/CSSAttribute.swift
  Aztec/Classes/Libxml2/DOM/Data/CSSAttributeType.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/Libxml2/DOM/Logic/CSS/BoldCSSAttributeMatcher.swift
  Aztec/Classes/Libxml2/DOM/Logic/CSS/CSSAttributeMatcher.swift
  Aztec/Classes/Libxml2/DOM/Logic/CSS/ItalicCSSAttributeMatcher.swift
  Aztec/Classes/Libxml2/DOM/Logic/CSS/UnderlineCSSAttributeMatcher.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
Labels: [Priority] High, [Type] Bug

#1063 Reorganizes the project a bit. Adds AttributeType.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Constants/HTMLConstants.swift
  Aztec/Classes/Converters/AttributesToStringAttributes/Base/ElementAttributeConverter.swift
  Aztec/Classes/Converters/AttributesToStringAttributes/Base/MainAttributesConverter.swift
  Aztec/Classes/Converters/AttributesToStringAttributes/Implementations/BoldElementAttributeConverter.swift
  Aztec/Classes/Converters/AttributesToStringAttributes/Implementations/ItalicElementAttributeConverter.swift
  Aztec/Classes/Converters/AttributesToStringAttributes/Implementations/UnderlineElementAttributeConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Base/AttachmentElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Base/ElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Base/FormatterElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/BRElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/CiteElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigcaptionElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigureElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/HRElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/ImageElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Base/ConditionalStringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Base/StringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/ConditionalConverters/ConditionalItalicStringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/CiteStringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/ItalicStringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/UnderlineStringAttributeConverter.swift
  Aztec/Classes/Formatters/Implementations/LinkFormatter.swift
  Aztec/Classes/Libxml2/Converters/In/InAttributeConverter.swift
  Aztec/Classes/Libxml2/DOM/Data/Attribute.swift
  Aztec/Classes/Libxml2/DOM/Data/AttributeType.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/NSAttributedString/Attributes/HTMLRepresentation.swift
  Aztec/Classes/NSAttributedString/Conversions/AttachmentToElementConverter/ImageAttachmentToElementConverter.swift
  Aztec/Classes/NSAttributedString/Conversions/AttachmentToElementConverter/VideoAttachmentToElementConverter.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/HTML/Conversions/HTMLParserTests.swift
  AztecTests/HTML/Nodes/ElementNodeTests.swift
  AztecTests/NSAttributedString/Conversions/AttributedStringSerializerTests.swift
  AztecTests/TextKit/HTMLRepresentationTests.swift
  AztecTests/TextKit/TextViewTests.swift
  AztecTests/TextKit/UnsupportedHTMLTests.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/CaptionShortcode/CaptionShortcodeOutputProcessor.swift
Labels: [Type] Tech Debt / Tech Task

#1064 Adds standard CSS attributes. Adds unit tests.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Libxml2/DOM/Data/CSSAttribute.swift
  Aztec/Classes/Libxml2/DOM/Data/CSSAttributeType.swift
  Aztec/Classes/Libxml2/DOM/Logic/CSS/BoldCSSAttributeMatcher.swift
  AztecTests/New Group/AttributesToStringAttributes/BoldElementAttributeConverterTests.swift
  AztecTests/New Group/AttributesToStringAttributes/ItalicElementAttributeConverterTests.swift
  AztecTests/New Group/AttributesToStringAttributes/UnderlineElementAttributeConverterTests.swift
Labels: [Type] Tech Debt / Tech Task

#1065 Try/add some more unit tests for paste fixes
  Aztec.xcodeproj/project.pbxproj
  AztecTests/New Group/StringAttributesToAttributes/BoldStringAttributeConverterTests.swift
  AztecTests/New Group/StringAttributesToAttributes/ItalicStringAttributeConverterTests.swift
  AztecTests/New Group/StringAttributesToAttributes/UnderlineStringAttributeConverterTests.swift
Labels: [Type] Tech Debt / Tech Task
