Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-06, with the labels that each got.

#966 Implements cite element
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/ElementConverters/Base/ElementConverter.swift
  Aztec/Classes/ElementConverters/Base/FormatterElementConverter.swift
  Aztec/Classes/ElementConverters/Implementations/CiteElementConverter.swift
  Aztec/Classes/Extensions/NSAttributedStringKey+Aztec.swift
  Aztec/Classes/Formatters/Implementations/CiteFormatter.swift
  Aztec/Classes/Libxml2/DOM/Data/Element.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  Aztec/Classes/TextKit/TextView.swift
  Example/Example/SampleContent/content.html
Labels: [Type] Enhancement

#965 Fix parsing of poster attribute on videos.
  Aztec/Classes/ElementConverters/Implementations/VideoElementConverter.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/SampleContent/content.html
Labels: [Type] Bug

#969 Update sample content for gutenberg.
  Example/Example/SampleContent/gutenberg.html
Labels: [Type] Enhancement

#975 Separates concerns in Plugin.
  Aztec/Classes/NSAttributedString/Conversions/HTMLConverter.swift
  Aztec/Classes/Plugin/Plugin.swift
  Aztec/Classes/Plugin/PluginManager.swift
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressInputCustomizer.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressOutputCustomizer.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressPlugin.swift
Labels: [Type] Tech Debt / Tech Task

#978 Make Gutenberg blocks mergeable
  Aztec/Classes/Libxml2/DOM/Data/Element.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: Gutenberg Compatibility, [Type] Bug

#979 Fixes gutenberg self-closing blocks.
  Example/Example/SampleContent/gutenberg.html
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/CommentNode+Gutenberg.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeNames.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: WordPressEditor, [Type] Enhancement

#981 Fix VideoPress processors
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/VideoShortcode/VideoShortcodeProcessor.swift
  WordPressEditor/WordPressEditorTests/Processors/ShortcodeProcessorTests.swift
Labels: [Type] Bug

#990 Issue/989 img alignment
  Aztec/Classes/NSAttributedString/Conversions/AttachmentToElementConverter/ImageAttachmentToElementConverter.swift
  Aztec/Classes/TextKit/ImageAttachment.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextStorageTests.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/AttachmentDetailsViewController.swift
Labels: Gutenberg Compatibility

#986 Fix single spaces are being removed
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  AztecTests/TextKit/TextStorageTests.swift
Labels: [Type] Bug

#985 Fix LI attributes lost
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/ElementConverters/Input/Implementations/GenericElementConverter.swift
  Aztec/Classes/Formatters/Implementations/LiFormatter.swift
  Aztec/Classes/Formatters/Implementations/TextListFormatter.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/TextKit/ParagraphProperty/HTMLLi.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
  AztecTests/TextKit/TextStorageTests.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: Gutenberg Compatibility

#992 Makes PRE mergeable while maintaining newlines.
  Aztec/Classes/Libxml2/DOM/Data/Element.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/SampleContent/content.html
Labels: [Type] Enhancement

#967 Make pre mergeable
  Aztec/Classes/Formatters/Implementations/PreFormatter.swift
  Aztec/Classes/Libxml2/DOM/Data/Element.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/SampleContent/content.html
Labels: Gutenberg Compatibility, [Type] Enhancement

#1000 Improve gb closing logic
  Aztec/Classes/Libxml2/DOM/Data/Element.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/Libxml2/DOM/Data/Node.swift
  Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/CommentNode+Gutenberg.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
Labels: Gutenberg Compatibility, WordPressEditor, [Bug-Type] Crash / Blocker, [Type] Bug

#996 Issue/994 crash gb missing closing element
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/Libxml2/DOM/Data/Node.swift
  Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/CommentNode+Gutenberg.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: Gutenberg Compatibility, [Bug-Type] Crash / Blocker, [Type] Discussion

#1001 Improve display of self-closing Gutenberg (Gutenpack) elements
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/TextKit/CommentAttachment.swift
  Aztec/Classes/TextKit/HTMLAttachment.swift
  Aztec/Classes/TextKit/RenderableAttachment.swift
  Aztec/Classes/TextKit/TextStorage.swift
  Example/Example/EditorDemoController.swift
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeDecoder.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenblockAttachment.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenblockConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackAttachment.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackAttachmentRenderer.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackAttachmentToElementConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressInputCustomizer.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressOutputCustomizer.swift
Labels: Gutenberg Compatibility
