Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-12, with the labels that each got.

#1097 Fixes the disappearing toolbar bug.
  .travis.yml
  Aztec/Classes/TextKit/TextView.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/EditorDemoController.swift
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTablePresenter.swift
  WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTableViewController.swift
Labels: [Priority] High, [Type] Bug

#1100 Don’t create ranges intersecting grapheme clusters
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/String+RangeConversion.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/Extensions/StringRangeConversionTests.swift
  AztecTests/Extensions/StringRangeMultibyteConversionTests.swift
Labels: [Bug-Type] Crash / Blocker, [Type] Bug

#1102 Fixes a bug in the paragraph ranges calculation.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/NSAttributedString+Lists.swift
  Aztec/Classes/Extensions/NSAttributedString+ParagraphRange.swift
  AztecTests/Extensions/NSAttributedStringListsTests.swift
  AztecTests/Extensions/NSAttributedStringParagraphRangeTests.swift
  AztecTests/Formatters/BlockquoteFormatterTests.swift
  AztecTests/Formatters/TextListFormatterTests.swift
Labels: [Type] Bug

#1105 Feature/add support for more embeds
  WordPressEditor/WordPressEditor/Classes/Processors/EmbedURLProcessor.swift
  WordPressEditor/WordPressEditorTests/Processors/EmbedURLProcessorTests.swift
Labels: [Type] Enhancement

#1107 Merges release/1.3.2 back into develop.
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: [Type] Tech Debt / Tech Task

#1108 Adding public access level HeaderFormatter
  Aztec/Classes/Formatters/Implementations/HTMLParagraphFormatter.swift
  Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
Labels: [Type] Tech Debt / Tech Task

#1109 Removes a verification that's no longer needed.
  Aztec/Classes/Formatters/Base/AttributeFormatter.swift
  Aztec/Classes/Formatters/Base/FontFormatter.swift
  Aztec/Classes/Formatters/Base/ParagraphAttributeFormatter.swift
  Aztec/Classes/Formatters/Base/StandardAttributeFormatter.swift
  Aztec/Classes/Formatters/Implementations/CodeFormatter.swift
  Aztec/Classes/TextKit/TextStorage.swift
Labels: [Type] Tech Debt / Tech Task

#1112 Fixes a crashing bug in GutenbergOutputHTMLTreeProcessor.
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessorTests.swift
Labels: [Priority] High, [Type] Bug

#1116 Fixes a bug that was stripping self-closing blocks.
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/HRElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
  Aztec/Classes/TextKit/TextStorage.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: [Type] Bug
