Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-11, with the labels that each got.

#1070 Proposal to fix pasting embeds
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/String+CharacterName.swift
  Aztec/Classes/Plugin/Plugin.swift
  Aztec/Classes/Plugin/PluginManager.swift
  Aztec/Classes/TextKit/TextView.swift
  Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/Embeds/WordPressPasteboardDelegate.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressPlugin.swift
  WordPressEditor/WordPressEditor/Classes/Processors/EmbedURLProcessor.swift
  WordPressEditor/WordPressEditorTests/Processors/EmbedURLProcessorTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: [Type] Bug, [Type] Enhancement

#1079 Fixes a bug that was causing certain HTML contents to be lost.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Converters/ElementsToAttributedString/Base/AttachmentElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Base/ElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/BRElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/CiteElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigcaptionElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigureElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/HRElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/ImageElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  AztecTests/New Group/ElementToAttributedString/GenericElementConverterTests.swift
  AztecTests/TextKit/TextStorageTests.swift
  AztecTests/TextKit/TextViewTests.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenblockConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverterTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: [Priority] High, [Type] Bug

#1080 Merges release/1.2 back into develop.
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: [Type] Tech Debt / Tech Task

#1081 Merges release/1.2 into master.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Converters/ElementsToAttributedString/Base/AttachmentElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Base/ElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/BRElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/CiteElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigcaptionElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigureElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/HRElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/ImageElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
  Aztec/Classes/Extensions/String+CharacterName.swift
  Aztec/Classes/Libxml2/DOM/Data/Attribute.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/Libxml2/DOM/Data/Node.swift
  Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  Aztec/Classes/Plugin/Plugin.swift
  Aztec/Classes/Plugin/PluginManager.swift
  Aztec/Classes/TextKit/MediaAttachment.swift
  Aztec/Classes/TextKit/ParagraphProperty/HTMLParagraph.swift
  Aztec/Classes/TextKit/ParagraphProperty/ParagraphProperty.swift
  Aztec/Classes/TextKit/TextView.swift
  Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
  AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
  AztecTests/New Group/ElementToAttributedString/GenericElementConverterTests.swift
  AztecTests/TextKit/TextStorageTests.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/SampleContent/gallery.html
  Example/Example/ViewController.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/Embeds/WordPressPasteboardDelegate.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenblockConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackAttachmentRenderer.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressPlugin.swift
  WordPressEditor/WordPressEditor/Classes/Processors/EmbedURLProcessor.swift
  WordPressEditor/WordPressEditorTests/Processors/EmbedURLProcessorTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverterTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: [Type] Tech Debt / Tech Task

#1082 Non breaking spaces are no longer removed by WordPressEditor.
  Aztec/Classes/Extensions/String+HTML.swift
  AztecTests/TextKit/TextViewTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: [Type] Bug

#1083 Fixes all unit tests in Xcode 10.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/ImageElementConverter.swift
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
  Aztec/Classes/Extensions/Array+Attribute.swift
  Aztec/Classes/NSAttributedString/Conversions/AttachmentToElementConverter/ImageAttachmentToElementConverter.swift
  Aztec/Classes/NSAttributedString/Conversions/AttachmentToElementConverter/VideoAttachmentToElementConverter.swift
  Aztec/Classes/TextKit/MediaAttachment.swift
  AztecTests/Renderers/CommentAttachmentRendererTests.swift
  AztecTests/Renderers/HTMLAttachmentRendererTests.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/AttachmentDetailsViewController.swift
  Example/Example/EditorDemoController.swift
  WordPressEditor/WordPressEditor/Classes/Extensions/ImageAttachment+WordPress.swift
  WordPressEditor/WordPressEditor/Classes/Extensions/MediaAttachment+WordPress.swift
  WordPressEditor/WordPressEditor/Classes/Extensions/VideoAttachment+WordPress.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryAttachmentToElementConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementConverter.swift
  WordPressEditor/WordPressEditorTests/Extensions/ImageAttachmentWordPressTests.swift
  WordPressEditor/WordPressEditorTests/Extensions/MediaAttachmentWordPressTests.swift
  WordPressEditor/WordPressEditorTests/Extensions/VideoAttachmentWordPressTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryAttachmentToElementConverterTests.swift
Labels: [Type] Tech Debt / Tech Task

#1084 Improves the HTML setter and getter for EditorView.
  Aztec/Classes/EditorView/EditorView.swift
Labels: [Type] Bug

#1089 Fix bugs with m.youtube URLs and IDs with dashes
  WordPressEditor/WordPressEditor/Classes/Processors/EmbedURLProcessor.swift
  WordPressEditor/WordPressEditorTests/Processors/EmbedURLProcessorTests.swift
Labels: [Type] Bug

#1088 Undo is no longer reset when switching editing modes.
  Aztec/Classes/EditorView/EditorView.swift
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Bug

#1092 Fix blockquote cite's removal.
  Aztec/Classes/Formatters/Implementations/CiteFormatter.swift
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Bug

#1093 Fix persistence of custom string attributes.
  Aztec/Classes/Extensions/NSAttributedString+Analyzers.swift
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Bug

#1094 Blockquote + cite is now ended when pressing ENTER.
  Aztec/Classes/Formatters/Base/FontFormatter.swift
  Aztec/Classes/Formatters/Implementations/FigcaptionFormatter.swift
  Aztec/Classes/Formatters/Implementations/FigureFormatter.swift
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Enhancement

#1095 Formatter identifiers are now extensible
  Aztec/Classes/GUI/FormatBar/FormattingIdentifier.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Enhancement

#1096 Remove the placeholderAttributes formatter property.
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/FigcaptionElementConverter.swift
  Aztec/Classes/Formatters/Base/AttributeFormatter.swift
  Aztec/Classes/Formatters/Base/FontFormatter.swift
  Aztec/Classes/Formatters/Implementations/FigcaptionFormatter.swift
  Aztec/Classes/Formatters/Implementations/FigureFormatter.swift
  Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/Formatters/HeaderFormatterTests.swift
  AztecTests/NSAttributedString/Conversions/AttributedStringParserTests.swift
  AztecTests/NSAttributedString/Conversions/AttributedStringSerializerTests.swift
Labels: [Type] Tech Debt / Tech Task
