Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-05, with the labels that each got.

#940 Fix editor layout and scroll
  Aztec/Classes/EditorView/EditorView.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Bug, [Type] Enhancement

#942 Data lost near comments.
  Aztec/Classes/ElementConverters/Implementations/FigureElementConverter.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/Libxml2/DOM/Data/Node.swift
  Aztec/Classes/Libxml2/DOM/Data/StandardElementType.swift
  Aztec/Classes/Libxml2/DOM/Data/TextNode.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  AztecTests/TextKit/TextStorageTests.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/SampleContent/gutenberg.html
  Example/Example/ViewController.swift
Labels: [Type] Bug

#945 Fixes unit tests, fixes newline inside single-line paragraph attributes.
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Type] Tech Debt / Tech Task

#954 Implements an initial version of the Plugin interface.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/ElementConverters/Base/ElementConverter.swift
  Aztec/Classes/Extensions/NSAttributedString+HTMLInitializer.swift
  Aztec/Classes/Plugin/Plugin.swift
  Aztec/Classes/Plugin/PluginsManager.swift
  Aztec/Classes/TextKit/TextStorage.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/Extensions/NSAttributedStringHTMLInitializerTests.swift
  AztecTests/HTML/Conversions/HTMLParserTests.swift
  Example/Example/EditorDemoController.swift
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Internals/AutoPProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Internals/CaptionShortcodeInputProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Internals/CaptionShortcodeOutputProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Internals/RemovePProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Internals/VideoShortcodeProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressPlugin.swift
  WordPressEditor/WordPressEditor/Classes/Processors/CalypsoProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Processors/VideoShortcodePostProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Processors/VideoShortcodePreProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Processors/WPVideoShortcodePreProcessor.swift
  WordPressEditor/WordPressEditorTests/AutoPProcessorTests.swift
  WordPressEditor/WordPressEditorTests/CaptionShortcodeInputProcessorTests.swift
  WordPressEditor/WordPressEditorTests/CaptionShortcodeOutputProcessorTests.swift
  WordPressEditor/WordPressEditorTests/RemovePProcessorTests.swift
Labels: [Type] Tech Debt / Tech Task

#957 Fixed EditorView's HTML source layout.
  Aztec/Classes/EditorView/EditorView.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Bug

#961 Fix replacement range on auto replaces for different sized text.
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Bug-Type] Crash / Blocker
