Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-07, with the labels that each got.

#1004 Makes the Example App cartfile private.
  Example/Cartfile.private
Labels: [Type] Tech Debt / Tech Task

#1006 Fixes a bug that was causing paragraphs to merge.
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Extensions/String+RegEx.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeDecoder.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeEncoder.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergAttributeNames.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenbergOutputHTMLTreeProcessor.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackAttachmentToElementConverter.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Gutenberg/GutenpackConverter.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenbergInputHTMLTreeProcessorTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/WordPressPluginTests.swift
Labels: [Priority] High, [Type] Bug

#1003 Try/reorganize sample content
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/SampleContent/content.html
  Example/Example/SampleContent/imagesOverlays.html
  Example/Example/ViewController.swift
Labels: [Type] Enhancement

#1014 Gutenberg code block delimiters are no longer removed.
  Aztec/Classes/Formatters/Implementations/PreFormatter.swift
  AztecTests/Formatters/PreFormaterTests.swift
Labels: WordPressEditor, [Type] Bug
