Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-08, with the labels that each got.

#1018 Fixes drag and drop images do not get `size-full` CSS class upon posting
  Aztec/Classes/TextKit/TextStorage.swift
Labels: [Type] Bug

#1021 Organizes some files and cleans up some code.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/StringUTF16+RangeConversion.swift
  AztecTests/Extensions/NSAttributedStringReplaceOcurrencesTests.swift
  AztecTests/Extensions/NSMutableAttributedStringParagraphProperty.swift
  AztecTests/Extensions/NSMutableAttributedStringReplaceOcurrencesTests.swift
  AztecTests/Extensions/StringEndOfLineTests.swift
  AztecTests/Extensions/StringRangeConversionTests.swift
  AztecTests/TextKit/ParagraphStyleTests.swift
  WordPressEditor/WordPressEditor/Classes/Extensions/String+RegEx.swift
Labels: [Type] Tech Debt / Tech Task

#1022 Fixes a crashing issue with regexes and Mn-class unicode characters.
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Extensions/String+RegEx.swift
  WordPressEditor/WordPressEditorTests/Extensions/StringRegExTests.swift
Labels: [Priority] High, [Type] Bug

#1025 Fixes an issue that was causing the default text color to sometimes change.
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Bug

#1026 Better support for pasting HTML in Aztec.
  Aztec/Classes/Extensions/UIPasteboard+Helpers.swift
  Aztec/Classes/TextKit/TextStorage.swift
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Enhancement

#1030 Improve pasting label
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Status] Not Ready For Review, [Type] Enhancement

#1031 Automated tests improvements. Crash fixed.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/NSAttributedString+Strip.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/TextKit/HTMLStorage.swift
  AztecTests/Processor/HTMLTreeProcessorTests.swift
  AztecTests/Renderers/CommentAttachmentRendererTests.swift
  AztecTests/TestingSupport/TextViewStub.swift
  AztecTests/TestingSupport/TextViewStubAttachmentDelegate.swift
  AztecTests/TestingSupport/TextViewStubDelegate.swift
  AztecTests/TextKit/HTMLStorageTests.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Bug-Type] Crash / Blocker, [Type] Bug, [Type] Tech Debt / Tech Task

#1035 Implements editing of target attribute in .A elements
  Aztec/Classes/Constants/HTMLConstants.swift
  Aztec/Classes/Formatters/Implementations/LinkFormatter.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/EditorDemoController.swift
  Example/Example/SampleContent/content.html
Labels: [Type] Enhancement

#1036 Removes an unused class, and a line of unused code.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Libxml2/DOM/Data/StandardAttribute.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
Labels: [Type] Tech Debt / Tech Task

#1038 Updated Gridicons to 0.16.
  Example/Cartfile.private
  Example/Cartfile.resolved
Labels: [Type] Tech Debt / Tech Task

#1043 Adds more unit tests.
  AztecTests/TextKit/TextViewTests.swift
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Classes/Extensions/ImageAttachment+WordPress.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/GalleryShortcode/GalleryAttachmentToElementConverter.swift
  WordPressEditor/WordPressEditor/Classes/Processors/ShortcodeProcessor.swift
  WordPressEditor/WordPressEditorTests/Extensions/ImageAttachmentWordPressTests.swift
  WordPressEditor/WordPressEditorTests/Extensions/MediaAttachmentWordPressTests.swift
  WordPressEditor/WordPressEditorTests/Extensions/VideoAttachmentWordPressTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/CaptionShortcode/CaptionShortcodeInputProcessorTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryAttachmentToElementConverterTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/GalleryShortcode/GalleryElementToTagConverterTests.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Gutenberg/GutenblockTests.swift
Labels: [Type] Tech Debt / Tech Task

#1042 Add no opener attribute when adding targets.
  Aztec/Classes/Constants/HTMLConstants.swift
  Aztec/Classes/Formatters/Implementations/LinkFormatter.swift
Labels: [Type] Enhancement
