Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2018-04, with the labels that each got.

#928 Xcode 9.3 support.
  Aztec.xcodeproj/project.pbxproj
  Aztec.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Aztec/Modulemaps/libxml2/libxml2-umbrella.h
  Aztec/Modulemaps/libxml2/module.modulemap
  Example/AztecExample.xcodeproj/project.pbxproj
  WordPress-Aztec-iOS.podspec
Labels: [Type] Tech Debt / Tech Task

#927 Fix caption processor
  Aztec/Classes/Libxml2/DOM/Data/Attribute.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/AztecExample.xcodeproj/xcshareddata/xcschemes/AztecExample.xcscheme
  Example/Example/CaptionShortcodePostProcessor.swift
  Example/Tests/CaptionShortcodePostProcessorTests.swift
Labels: [Type] Enhancement

#929 Fix Travis: Xcode 9.3 support and more.
  .travis.yml
Labels: [Type] Tech Debt / Tech Task

#931 Updates README.md.
  README.md
Labels: [Type] Documentation

#935 Fix Xcode 9.3 warnings.
  Aztec.xcodeproj/project.pbxproj
  Aztec.xcodeproj/xcshareddata/xcschemes/Aztec.xcscheme
  Aztec.xcodeproj/xcshareddata/xcschemes/Carthage Update.xcscheme
  Aztec/Classes/Extensions/String+RangeConversion.swift
  Aztec/Classes/GUI/FormatBar/FormatBar.swift
  Aztec/Classes/Libxml2/Converters/In/CSSParser.swift
  Aztec/Classes/Libxml2/DOM/Data/Attribute.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/TextKit/ParagraphStyle.swift
  AztecTests/Formatters/TextListFormatterTests.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/AztecExample.xcodeproj/xcshareddata/xcschemes/AztecExample.xcscheme
  Example/AztecUITests/AztecUITests.swift
  Example/AztecUITests/FormattingTests.swift
  Example/AztecUITests/HighPriorityIssuesTests.swift
  Example/AztecUITests/ImagesTests.swift
  Example/AztecUITests/LinkTests.swift
  Example/Example/Images.xcassets/AppIcon.appiconset/Contents.json
  Example/Example/Images.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
Labels: [Type] Tech Debt / Tech Task

#919 Use set instead of array for formatting identifiers.
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Enhancement
