Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2019-04, with the labels that each got.

#1157 Empty list
  Aztec/Classes/Extensions/String+EndOfLine.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Type] Bug

#1169 Update podspec versions to 1.5.2
  Aztec/Classes/Extensions/String+EndOfLine.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  AztecTests/TextKit/TextViewTests.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: Gutenberg Compatibility

#1166 Fix a crash when system pasteboard is empty
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Bug-Type] Crash / Blocker

#1165 Add test to check nested list output.
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Type] Bug

#1175 Refactor TextView key commands.
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Enhancement

#1178 Fix AutoPProcessor for Swift 5
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor/Classes/Extensions/String+RegEx.swift
  WordPressEditor/WordPressEditorTests/WordPressPlugin/Calypso/AutopRemovep/AutoPProcessorTests.swift
Labels: WordPressEditor, [Bug-Type] Crash / Blocker, [Priority] High
