Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2019-02, with the labels that each got.

#1134 Adds the Code of Conduct to Aztec.
  CODE-OF-CONDUCT.md
Labels: [Type] Documentation

#1138 Fix bold converting issue.
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift
  Aztec/Classes/Libxml2/DOM/Data/Element.swift
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
  AztecTests/New Group/StringAttributesToAttributes/BoldStringAttributeConverterTests.swift
Labels: [Type] Bug

#1139 Standardize string-attribute-conversion logic.
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/ItalicStringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/UnderlineStringAttributeConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Utility/HTMLStyleToggler.swift
  Aztec/Classes/Extensions/Dictionary+AttributedStringKey.swift
  AztecTests/New Group/StringAttributesToAttributes/ItalicStringAttributeConverterTests.swift
Labels: [Type] Tech Debt / Tech Task

#1136 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: [Type] Documentation

#1145 Removes .travis.yml file.
  .travis.yml
Labels: [Type] Tech Debt / Tech Task

#1141 Removes iOS 11 formatting workarounds
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Type] Tech Debt / Tech Task

#924 Refresh media attachment's identifier after paste
  Aztec/Classes/Extensions/NSAttributedString+Attachments.swift
  Aztec/Classes/TextKit/MediaAttachment.swift
Labels: [Type] Bug

#1146 Fix update of typing attributes when moving range.
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Bug
