Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2019-06, with the labels that each got.

#1190 Make sure that standalone block elements are kept.
  Aztec/Classes/Libxml2/DOM/Data/ElementNode.swift
Labels: [Type] Bug

#1198 Allow configuration of text color
  Aztec/Classes/TextKit/TextView.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Enhancement

#1199 Make available method to extract HTML from a string.
  Aztec/Classes/TextKit/TextStorage.swift
Labels: [Type] Enhancement

#1201 Allow replacement of last empty line on Aztec
  Aztec/Classes/NSAttributedString/Conversions/HTMLConverter.swift
  Aztec/Classes/TextKit/TextStorage.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextStorageTests.swift
Labels: [Type] Enhancement

#1200 Notify changes on TextView only on user events
  Aztec/Classes/Extensions/UITextView+Delegate.swift
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Enhancement

#1202 Update CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: [Type] Enhancement

#1203 Issue/fix crash on toggle quotes
  Aztec/Classes/Extensions/NSMutableAttributedString+ReplaceOcurrences.swift
  AztecTests/Extensions/NSMutableAttributedStringReplaceOcurrencesTests.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Bug-Type] Crash / Blocker
