Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2019-03, with the labels that each got.

#1144 Fixes instruments profiling.
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
Labels: [Type] Tech Debt / Tech Task

#1154 Issue/1153 support for source elements inside videos
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/VideoElementConverter.swift
  Aztec/Classes/Libxml2/DOM/Data/Element.swift
  Aztec/Classes/NSAttributedString/Conversions/AttachmentToElementConverter/VideoAttachmentToElementConverter.swift
  Aztec/Classes/TextKit/MediaAttachment.swift
  Aztec/Classes/TextKit/VideoAttachment.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/EditorDemoController.swift
  Example/Example/SampleContent/video.html
  Example/Example/SampleContent/videoShortcodes.html
  Example/Example/ViewController.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor/Classes/Extensions/ImageAttachment+WordPress.swift
  WordPressEditor/WordPressEditor/Classes/Extensions/MediaAttachment+WordPress.swift
  WordPressEditor/WordPressEditor/Classes/Extensions/VideoAttachment+WordPress.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/Calypso/VideoShortcode/VideoShortcodeProcessor.swift
  WordPressEditor/WordPressEditorTests/Processors/ShortcodeProcessorTests.swift
Labels: [Type] Bug, [Type] Enhancement

#1161 Use video shortcodes processors on Gutenberg.
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressInputCustomizer.swift
  WordPressEditor/WordPressEditor/Classes/Plugins/WordPressPlugin/WordPressOutputCustomizer.swift
Labels: Gutenberg Compatibility
