Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2019-11, with the labels that each got.

#1229 Make pre and quote background colors optional
  Aztec/Classes/TextKit/LayoutManager.swift
  Aztec/Classes/TextKit/TextView.swift
  Example/Example/EditorDemoController.swift
Labels: Gutenberg Compatibility

#1230 Release/1.12.0
  .circleci/config.yml
  Aztec/Classes/TextKit/LayoutManager.swift
  Aztec/Classes/TextKit/TextView.swift
  Example/Example/Base.lproj/Main.storyboard
  Example/Example/EditorDemoController.swift
  Example/Example/ViewController.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTableViewController.swift
Labels: Release process

#1231 Update Develop from Master after 1.12.0 Release
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: Release process

#1235 Update reference images for image resize tests.
  AztecTests/Resources/UIImageResizeImage1_3x.png.dat
  AztecTests/Resources/UIImageResizeImage2_3x.png.dat
  WordPressEditor/WordPressEditorTests/Resources/GutenpackAttachmentRender_3x.png.dat
Labels: [Type] Automated Testing

#1237 Fix copy/paste of attributed string from app without support for dark/light mode
  Aztec/Classes/TextKit/TextView.swift
  Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Bug

#1238 Issue/make metrics configurable
  Aztec/Classes/Constants/Metrics.swift
  Aztec/Classes/TextKit/LayoutManager.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Enhancement

#1239 Release/1.13.0
  Aztec/Classes/Constants/Metrics.swift
  Aztec/Classes/TextKit/LayoutManager.swift
  Aztec/Classes/TextKit/MediaAttachment.swift
  Aztec/Classes/TextKit/TextView.swift
  Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
  AztecTests/Resources/UIImageResizeImage1_3x.png.dat
  AztecTests/Resources/UIImageResizeImage2_3x.png.dat
  AztecTests/TextKit/TextViewTests.swift
  CHANGELOG.md
  Example/Example/EditorDemoController.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditorTests/Extensions/MediaAttachmentWordPressTests.swift
  WordPressEditor/WordPressEditorTests/Resources/GutenpackAttachmentRender_3x.png.dat
Labels: Release process

#1240 Merge master with version 1.13.0 to develop
  CHANGELOG.md
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: Release process

#1242 Implement start and reversed in lists.
  Aztec/Classes/Extensions/NSAttributedString+Lists.swift
  Aztec/Classes/Libxml2/DOM/Data/AttributeType.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringParser.swift
  Aztec/Classes/TextKit/LayoutManager.swift
  Aztec/Classes/TextKit/ParagraphProperty/TextList.swift
  AztecTests/Formatters/TextListFormatterTests.swift
  Example/Example/SampleContent/content.html
Labels: Gutenberg Compatibility, [Type] Enhancement
