Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2019-12, with the labels that each got.

#1243 Implements a Color provider
  Aztec.xcodeproj/project.pbxproj
  Aztec/Assets/html_colors.json
  Aztec/Classes/Converters/AttributesToStringAttributes/Implementations/ForegroundColorElementAttributeConverter.swift
  Aztec/Classes/Formatters/Implementations/CodeFormatter.swift
  Aztec/Classes/TextKit/ColorProvider.swift
  Example/Example/SampleContent/content.html
Labels: [Type] Enhancement

#1247 Compatibility with xcode 10
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/TextKit/ColorProvider.swift
  Aztec/Classes/TextKit/TextView.swift
  Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
  config/XCodeVersion.xcconfig
Labels: [Priority] High

#1248 Hotfix 1.14.1
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/TextKit/ColorProvider.swift
  Aztec/Classes/TextKit/TextView.swift
  Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
  CHANGELOG.md
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  config/XCodeVersion.xcconfig
Labels: Release process

#1249 Merge master back to develop (hotfix 1.14.1)
  CHANGELOG.md
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: Release process

#1245 Set default text color when text color is changed.
  Aztec/Classes/TextKit/TextView.swift
Labels: [Type] Bug

#1251 Fix placeholder images when in dark mode
  Aztec/Assets/Media.xcassets/image.imageset/Contents.json
  Aztec/Assets/Media.xcassets/image.imageset/gridicons-image-dark.pdf
  Aztec/Classes/TextKit/MediaAttachment.swift
  Aztec/Classes/TextKit/TextView.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/EditorDemoController.swift
  Example/Example/SampleContent/failedMedia.html
  Example/Example/ViewController.swift
Labels: [Type] Bug

#1246 Improve “More” button accessibility
  Aztec/Classes/GUI/FormatBar/FormatBar.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: [Type] Enhancement
