Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2019-10, with the labels that each got.

#1216 Making popovert presentation background color dynamic
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTablePresenter.swift
Labels: [Type] Enhancement

#1218 Release v1.10.1
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTablePresenter.swift
Labels: Release process

#1215 Issue/703 fix color styling
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Converters/AttributesToStringAttributes/Implementations/ForegroundColorElementAttributeConverter.swift
  Aztec/Classes/Libxml2/DOM/Data/CSSAttributeType.swift
  Aztec/Classes/Libxml2/DOM/Logic/CSS/ForegroundColorCSSAttributeMatcher.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  AztecTests/TextKit/TextViewTests.swift
Labels: [Type] Bug

#1221 Allow configuration of default fonts used in TextView
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Extensions/NSMutableAttributedString+ReplaceAttributes.swift
  Aztec/Classes/Formatters/Implementations/CodeFormatter.swift
  Aztec/Classes/Formatters/Implementations/PreFormatter.swift
  Aztec/Classes/TextKit/FontProvider.swift
  Aztec/Classes/TextKit/LayoutManager.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Enhancement

#1222 Update project to have iOS 11 has a minimum
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/EditorView/EditorView.swift
  Aztec/Classes/GUI/FormatBar/FormatBar.swift
  Aztec/Classes/TextKit/FontProvider.swift
  Aztec/Classes/TextKit/ParagraphProperty/Header.swift
  Aztec/Classes/TextKit/TextView.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/EditorDemoController.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
Labels: [Type] Enhancement

#1225 Release v1.11.0
  .circleci/config.yml
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Converters/AttributesToStringAttributes/Implementations/ForegroundColorElementAttributeConverter.swift
  Aztec/Classes/EditorView/EditorView.swift
  Aztec/Classes/Extensions/NSMutableAttributedString+ReplaceAttributes.swift
  Aztec/Classes/Formatters/Implementations/CodeFormatter.swift
  Aztec/Classes/Formatters/Implementations/PreFormatter.swift
  Aztec/Classes/GUI/FormatBar/FormatBar.swift
  Aztec/Classes/Libxml2/DOM/Data/CSSAttributeType.swift
  Aztec/Classes/Libxml2/DOM/Logic/CSS/ForegroundColorCSSAttributeMatcher.swift
  Aztec/Classes/NSAttributedString/Conversions/AttributedStringSerializer.swift
  Aztec/Classes/TextKit/FontProvider.swift
  Aztec/Classes/TextKit/LayoutManager.swift
  Aztec/Classes/TextKit/ParagraphProperty/Header.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/TextKit/TextViewTests.swift
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/EditorDemoController.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
Labels: Release process

#1226 Merge master back to develop
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: Release process

#1223 Update demo for dark mode
  Example/Example/Base.lproj/Main.storyboard
  Example/Example/EditorDemoController.swift
  Example/Example/ViewController.swift
  WordPressEditor/WordPressEditor/Classes/ViewControllers/OptionsTableViewController/OptionsTableViewController.swift
Labels: [Type] Enhancement

#1228 Recalculate typing attributes on alignment update
  Aztec/Classes/TextKit/TextView.swift
Labels: Gutenberg Compatibility
