Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2020-03, with the labels that each got.

#1272 Prepare release 1.17.0
  Aztec/Classes/TextKit/LayoutManager.swift
  CHANGELOG.md
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/SampleContent/content.html
  Example/Example/SampleContent/underline.html
  Example/Example/ViewController.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: Release process

#1274 Update gridicons to 1.0
  Example/Cartfile.private
  Example/Cartfile.resolved
  Example/Example/EditorDemoController.swift
  Example/Example/MediaInserter.swift
  Example/Example/TextViewAttachmentDelegateProvider.swift
Labels: [Type] Tech Debt / Tech Task

#1275 Fix underline bug
  Aztec/Classes/TextKit/LayoutManager.swift
  CHANGELOG.md
  Example/Example/SampleContent/underline.html
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
Labels: [Type] Bug
