Repository wordpress-mobile/AztecEditor-iOS, pull requests merged in 2020-01, with the labels that each got.

#1253 Issue/1086 blockquote multilevel support
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
  Aztec/Classes/Formatters/Implementations/BlockquoteFormatter.swift
  Aztec/Classes/Formatters/Implementations/TextListFormatter.swift
  Aztec/Classes/TextKit/LayoutManager.swift
  Aztec/Classes/TextKit/ParagraphStyle.swift
  Aztec/Classes/TextKit/TextView.swift
  Example/Example/EditorDemoController.swift
Labels: [Type] Enhancement

#1261 Issue/refactor demo app
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/EditorDemoController.swift
  Example/Example/MediaInserter.swift
  Example/Example/TextViewAttachmentDelegateProvider.swift
  Example/Example/UIImage+SaveTo.swift
Labels: [Type] Enhancement

#1262 Allow to use headers without bold/shadow traits
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift
  Aztec/Classes/Formatters/Base/ParagraphAttributeFormatter.swift
  Aztec/Classes/Formatters/Implementations/BoldFormatter.swift
  Aztec/Classes/Formatters/Implementations/BoldWithShadowForHeadingFormatter.swift
  Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
  Aztec/Classes/TextKit/Configuration.swift
  Aztec/Classes/TextKit/TextView.swift
  AztecTests/Formatters/BoldFormatterTests.swift
  AztecTests/Formatters/HeaderFormatterTests.swift
  AztecTests/TextKit/TextStorageTests.swift
Labels: [Type] Enhancement

#1255 Revert "Compatibility with xcode 10"
  Aztec.xcodeproj/project.pbxproj
  Aztec/Classes/TextKit/ColorProvider.swift
  Aztec/Classes/TextKit/TextView.swift
  Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
  config/XCodeVersion.xcconfig
Labels: [Type] Tech Debt / Tech Task

#1263 Prepare Release 1.15.0
  Aztec.xcodeproj/project.pbxproj
  Aztec/Assets/Media.xcassets/image.imageset/Contents.json
  Aztec/Assets/Media.xcassets/image.imageset/gridicons-image-dark.pdf
  Aztec/Classes/Converters/ElementsToAttributedString/Implementations/GenericElementConverter.swift
  Aztec/Classes/Converters/StringAttributesToAttributes/Implementations/BoldStringAttributeConverter.swift
  Aztec/Classes/Formatters/Base/ParagraphAttributeFormatter.swift
  Aztec/Classes/Formatters/Implementations/BlockquoteFormatter.swift
  Aztec/Classes/Formatters/Implementations/BoldFormatter.swift
  Aztec/Classes/Formatters/Implementations/BoldWithShadowForHeadingFormatter.swift
  Aztec/Classes/Formatters/Implementations/HeaderFormatter.swift
  Aztec/Classes/Formatters/Implementations/TextListFormatter.swift
  Aztec/Classes/GUI/FormatBar/FormatBar.swift
  Aztec/Classes/TextKit/ColorProvider.swift
  Aztec/Classes/TextKit/Configuration.swift
  Aztec/Classes/TextKit/LayoutManager.swift
  Aztec/Classes/TextKit/MediaAttachment.swift
  Aztec/Classes/TextKit/ParagraphStyle.swift
  Aztec/Classes/TextKit/TextView.swift
  Aztec/Classes/TextKit/TextViewPasteboardDelegate.swift
  Aztec/Info.plist
  AztecTests/Formatters/BoldFormatterTests.swift
  AztecTests/Formatters/HeaderFormatterTests.swift
  AztecTests/TextKit/TextStorageTests.swift
  CHANGELOG.md
  Example/AztecExample.xcodeproj/project.pbxproj
  Example/Example/EditorDemoController.swift
  Example/Example/MediaInserter.swift
  Example/Example/SampleContent/failedMedia.html
  Example/Example/TextViewAttachmentDelegateProvider.swift
  Example/Example/UIImage+SaveTo.swift
  Example/Example/ViewController.swift
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Info.plist
  config/XCodeVersion.xcconfig
Labels: Release process

#1265 Brings release 1.15.0 release changes to develop
  Aztec.xcodeproj/project.pbxproj
  Aztec/Info.plist
  CHANGELOG.md
  WordPress-Aztec-iOS.podspec
  WordPress-Editor-iOS.podspec
  WordPressEditor/WordPressEditor.xcodeproj/project.pbxproj
  WordPressEditor/WordPressEditor/Info.plist
Labels: Release process
